language: node_js

node_js:
  - "0.11"
  - "0.10"

before_script:
  - 'npm install -g bower grunt-cli karma'
  - 'npm install karma-phantomjs-launcher –save-dev'
  - 'bower install'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'

script: grunt